service: lambda-fastify-nestjs
app: lambda-fastify-nestjs
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: GET
          path: /{proxy+}

plugins:
  - serverless-offline
  # - serverless-plugin-typescript
