service: lambda-fastify-nestjs
frameworkVersion: "^4.0.0"
app: lambda-fastify-nestjs
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_URL: "${env:DYNAMODB_URL}"
    TABLE_NAME: "${env:TABLE_NAME}"
    REDIS_HOST: "${env:REDIS_HOST}"
    REDIS_PORT: "${env:REDIS_PORT}"
    REDIS_USE_CLUSTER: "${env:REDIS_USE_CLUSTER}"
configValidationMode: error
useDotenv: true

functions:
  main:
    handler: dist/lambda.handler
    timeout: "${env:TIMEOUT}"
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: /{proxy+}
      - http:
          method: DELETE
          path: /{proxy+}
custom:
  prune:
    automatic: true
    number: 2
  addHttpOffline:
    dev: []
    local:
      - httpApi:
          method: "GET"
          path: "/{proxy+}"
plugins:
  - serverless-offline
