service: lambda-fastify-nestjs
frameworkVersion: "^4.0.0"
app: lambda-fastify-nestjs
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
configValidationMode: error
useDotenv: true

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: /{proxy+}
custom:
  prune:
    automatic: true
    number: 2
  addHttpOffline:
    dev: []
    local:
      - httpApi:
          method: "GET"
          path: "/{proxy+}"

plugins:
  - serverless-offline
